language: r
cache: packages
pandoc_version: 1.17.2

branches:
  only: source

script:
  - sudo apt-get install libxml2 -y
  - Rscript -e 'servr:::knit_maybe(c(".", "_source", "_posts"), c(".", "_posts", "_posts"), "build.R", "jekyll")'
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  target_branch: master
